- kernel:
      input: "test.csv"
      output: "test_output"
      force_replacement: True
      clean: False
      debug: False
      prepare_data:
          cols: I0 J0 STEP_I STEP_J N M
          rows: { "I0": 0 }
          target: FLOPSs
          norm:
              enabled: False
              type: None
          categories:
              num: 6
              type: "linear"
              scale_factor: 1e9
      classification:
          type: "decisiontree" # randomforest
          dt_settings:
              max_depth: 10
              max_leaves: 50
              criterion: "gini"
              min_score: 0.8
              pruning_mccp_alpha: 0.0
              text_tree: True
              graph_tree: True
              orientation: "vertical"
      recommender:
          pred: FLOPSs
          interest_dim:
              value: 6.5
              type: numeric
          dim: I J It Jt Is Js Jters Iters NELEMS
