# File              : config.yml
# Author            : Marcos Horro <marcos.horro@udc.gal>
# Date              : Mér 06 Nov 2019 16:36:12 MST
# Last Modified Date: Ven 15 Nov 2019 15:37:57 MST
# Last Modified By  : Marcos Horro <marcos.horro@udc.gal>
#
# example file, this file should be used for executing with wrapper.py
# POSSIBLE VALUES
#- general:
#    input: # existing valid filename
#    output: # valid filename
#    overwrite: # True/False
#    clean: # True/False, for cleaning temp files
#    debug: # True/False, for printing debug outputs
#- prepare_data:
#    cols: # columns to use for DT
#    rows: # filtering rows in CSV
#    pred: # dimension to predict
#    norm: # norm values
#       enabled: # True/False
#       type: # z-score/minmax; useless if norm: False
#    cats:
#       num: # use 0 for discrete values, value greater than 1 in other case
#       scale_factor: # if numeric, could be convenient to scale numbers
#    dt_settings: # decision tree parameters
#       alg: # REPTree or J48 right now (both tested)
#       params: # e.g. M 5 N 1 (minimum 5 instances, 1 fold), or ''
#       opts: # opts split by space, e.g. "\"B R U\""
#    min_acc: # minimum accuracy accepted of DT
#- recommender:
#    pred: # dimension to predict
#    interest_dim:
#       value: # value of interest of prediction
#       type: # numeric/nominal (categorial also called)
#    dim: # dimensions we want to know, analogous value == cols in
#                 prepare_data

- general:
      input: "test/test_marta.csv"
      output: "marta-random.arff"
      overwrite: True
      clean: True
      debug: False
- prepare_data:
      cols: X_0 X_1 X_2 X_3 CFG
      rows: ""
      pred: FLOPSs
      norm:
          enabled: False
          type: None
      cats:
          num: 25
          type: "linear"
          scale_factor: 1e10
      dt_settings:
          max_depth: J48
          
      min_acc: 0.1
- recommender:
      pred: FLOPSs
      interest_dim:
          value: 7.9
          type: numeric
      dim: X_0 X_1 X_2 X_3 CFG
