- kernel:
      name: "micro_codelet"
      path: "kernels/micro_codelet"
      description: "Setup for micro_codelets"
      debug: False
      show_progress_bars: True
      preamble:
          command: "rm -Rf bin asm_codes && sudo cpupower frequency-set -u 2.1GHz && sudo cpupower frequency-set -d 2.1GHz"
      finalize:
          clean_tmp_files: False
          clean_asm_files: False
          clean_bin_files: False
          command: ""
      compilation:
          enabled: True
          processes: 32
          language: "C"
          compiler_flags: 
            { 
                #"gcc": " -O3 -mtune=cascadelake -fno-loop-interchange -flto -ftree-vectorize -fsimd-cost-model=unlimited -fvect-cost-model=unlimited ",
                "icc": " -O3 -mtune=cascadelake -ipo -ffat-lto-objects -ftree-vectorize -vec-threshold0 -inline-forceinline ",
            }
          common_flags: "  "
          asm_analysis: True 
          debug: False
      configuration:
          kernel_cfg: [" -mavx512f -mfma -mprefer-vector-width=512 ", " -mfma -mavx2 ", " -msse4.2 "]
          macveth_flags: " -misa=avx2 "
          features:
                MICRO_CODELET_FILE_NAME:
                    evaluate: True
                    type: "static"
                    val_type: "string"
                    value: "[f\"patterns/codelet_{i:08d}.c\" for i in range(1)]"
                ORIG_y:
                    evaluate: True
                    type: "static"
                    val_type: "numeric"
                    value: "[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]"
                ORIG_A:    
                    evaluate: True
                    type: "static"
                    val_type: "numeric"
                    value: "[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]"
                ORIG_x:    
                    evaluate: True
                    type: "static"
                    val_type: "numeric"
                    value: "[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]"
          flops: "592"
      execution:
          enabled: True
          papi_counters: [
            "CPU_CLK_THREAD_UNHALTED:THREAD_P",
            "UNHALTED_REFERENCE_CYCLES",
            "UOPS_EXECUTED:STALL_CYCLES",
            "PAPI_RES_STL",
            "INST_RETIRED:ANY_P",
            "UOPS_ISSUED:ALL",
            "UOPS_RETIRED:ALL",
            "FP_ARITH:SCALAR_DOUBLE",
            "FP_ARITH:128B_PACKED_DOUBLE",
            "FP_ARITH:256B_PACKED_DOUBLE",
            "FP_ARITH:512B_PACKED_DOUBLE",
            "PAPI_BR_TKN",
            "PAPI_BR_MSP",
            "MEM_LOAD_UOPS_RETIRED:L1_HIT",
            "MEM_LOAD_UOPS_RETIRED:L1_MISS",
            "ICACHE_64B:IFTAG_HIT",
            ]
          threshold_outliers: 3
          mean_and_discard_outliers: False
          nexec: 5
          nsteps: 1000
          cpu_affinity: 11
          prefix: ""
      output:
          name: "default"
          columns: "all"
          report: True
          verbose: True
