- kernel:
      name: "micro_codelet"
      path: "kernels/micro_codelet"
      description: "Setup for micro_codelets"
      debug: False
      show_progress_bars: True
      preamble:
          command: "sudo cpupower frequency-set -u 2.1GHz && sudo cpupower frequency-set -d 2.1GHz"
      finalize:
          clean_tmp_files: False
          clean_asm_files: False
          clean_bin_files: False
          command: ""
      compilation:
          need_to_compile: True
          language: "C"
          compiler_flags: 
            { 
                "gcc": " -O3 -march=native -ftree-vectorize -flto ",
                #"icc": " -O3 -ipo -ftree-vectorize -vec-threshold0 -inline-forceinline",
            }
          common_flags: "  "
          asm_analysis: True 
          debug: False
      configuration:
          parallelism: 16
          kernel_cfg: [ " -mavx2 "]
          macveth_flags: " -misa=avx2 "
          features:
                MICRO_CODELET_FILE_NAME:
                    evaluate: True
                    type: "static"
                    val_type: "string"
                    value: "[f\"patterns/codelet_{i:08d}.c\" for i in range(1)]"
                ORIG_y:
                    evaluate: True
                    type: "static"
                    val_type: "numeric"
                    value: "[0,1,2,3,4,5,6,7]"
                    #value: "[0]"
                ORIG_A:    
                    evaluate: True
                    type: "static"
                    val_type: "numeric"
                    #value: "[0,1,2,3,4,5,6,7]"
                    value: "[0]"
                ORIG_x:    
                    evaluate: True
                    type: "static"
                    val_type: "numeric"
                    #value: "[0,1,2,3,4,5,6,7]"
                    value: "[0]"
          flops: "0"
      execution:
          papi_counters: [
                "CPU_CLK_THREAD_UNHALTED:THREAD_P", 
                "UNHALTED_REFERENCE_CYCLES",
                "INST_RETIRED:ANY_P",
                "UOPS_ISSUED:ALL",
                "UOPS_RETIRED:ALL",
                "PAPI_SP_OPS", 
                "PAPI_VEC_SP",
                "PAPI_DP_OPS", 
                "PAPI_VEC_DP",
                "PAPI_BR_TKN",
                "PAPI_BR_MSP",
                ]
          threshold_outliers: 3
          mean_and_discard_outliers: False
          nexec: 5
          nruns: 1000
          cpu_affinity: 11
          prefix: ""
      output:
          name: "default"
          columns: "all"
          report: True
          verbose: True
