language: python
python:
  - "3.6" # current default Python on Travis CI
  - "3.7"
  - "3.8"
before_install:
  - pip install -U pip
#  - pip install codecov
# command to install dependencies
install:
  - pip install -r requirements.txt
# tests to execute
script:
  - pytest