language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
before_install:
  - pip install --upgrade pip
  - pip install codecov
  - pip install build
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python -m build
# tests to execute
script:
  - pytest
