[build-system]
requires = ["setuptools >= 54.0.0", "wheel", "setuptools_scm>=6.2"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/marta/_version.py"

# [tool.black]
# line-length = 100