# (c) Copyright 2019-2020 the Colorado State University.
# (c) Copyright 2020 Universidade da Coruña.
#
#
# Contact:
#   Marcos Horro Varela <marcos.horro@udc.es>
#   Louis-Noël Pouchet <pouchet@colostate.edu>
#
# #############################################################################
#
# Example file, this file should be used for executing with profiler.py
# There is a - kernel for each program
# An example could be:
# - kernel:
#       target: "kernel_redux.c"
#       path: "kernels/reductions"
#       compilation:
#           compiler: ["gcc"]
#           kernel_cfg: ["-DKERNEL=REDUX -DSTMT=1", "-DKERNEL=REDUX -DSTMT=2"]
#           features:
#             init_val_i: [0]
#             init_val_j: [0]
#             tile_size_i: [1]
#             tile_size_j: [1]
#             step_size_i: [1]
#             step_size_j: [1]
#           nexec: 7
#           nruns: 100000
#           flops: "2*ceil(tile_size_i/step_size_i)*ceil(tile_size_j/step_size_j)" 
#           common_flags: "-DPOLYBENCH_USE_C99_PROTO -DPOLYBENCH_USE_RESTRICT
#           -Ofast -ftree-vectorize -march=native -mtune=native
#           -fvect-cost-model=unlimited -fsimd-cost-model=unlimited -mavx2
#           -ftree-vectorizer-verbose=7 --param min-vect-loop-bound=1"
#           output_cols: "all"
#           debug: True
#       execution:
#           th_pin: "OMP_NUM_THREADS=1 GOMP_CPU_AFFINITY=7"
#           debug: False
#
# #############################################################################

- kernel:
      name: "randomvectorpacking"
      main_src: "main.cc"
      target_src: "randompacking.cc"
      descr: ""
      path: "kernels/randompacking"
      debug: False
      tmp_files: "keep"
      compilation:
          compiler: "gcc"
          kernel_cfg: ["NPACK=4 MACVETH=true", "NPACK=4"]
          features:
            X_: "it.combinations(range(0, 5), 4)"
            # X_0: [0]
            # X_1: [1]
            # X_2: [2,54]
            # X_3: [3,18]
          macveth: True
          nexec: 7
          nruns: 1000000
          flops: "4*2"
          fixed_flags: " -DNPACK=4 "
          common_flags: "-ftree-vectorize -march=native -mtune=native
          -fvect-cost-model=unlimited -fsimd-cost-model=unlimited
          -ftree-vectorizer-verbose=7 --param min-vect-loop-bound=1"
          silent: True
      execution:
          args: "OMP_NUM_THREADS=1 GOMP_CPU_AFFINITY=7"
      output:
          name: ""
          dir: "./"
          columns: "all"
          verbose: True