# (C) Copyright 2019-2020 the Colorado State University.
#
# Contact:
#   Marcos Horro Varela <marcos.horro@udc.es>
#   Louis-Noël Pouchet <pouchet@colostate.edu>
#
# #############################################################################
#
# Example file, this file should be used for executing with profiler.py
# There is a - kernel for each program
# An example could be:
# - kernel:
#     source: "kernel_redux.c"
#     compilation:
#         compiler: ["gcc"]
#         kernel_cfg: ["-DKERNEL=REDUX -DSTMT=1","-DKERNEL=REDUX -DSTMT=2"]
#         init_val: [0, 1]
#         tile_size: [1, 2]
#         step_size: [1, 2]
#         nexec: 7
#         nruns: 1000000
#         flops: 2
#         custom_flags: # string containing custom flags
#         debug: # True/False
#     execution:
#         th_pin: # Thread pinning, e.g. for gcc "OMP_NUM_THREADS=1
#                 #  GOMP_CPU_AFFINITY=1"
#         debug: # True/False
#
# #############################################################################

- kernel:
      source: "kernel_redux.c"
      compilation:
          compiler: ["gcc"]
          kernel_cfg: ["-DKERNEL=REDUX -DSTMT=1", "-DKERNEL=REDUX -DSTMT=2"]
          init_val: [0]
          tile_size: [1]
          step_size: [1]
          nexec: 7
          nruns: 100000
          flops: 2
          custom_flags: "-DPOLYBENCH_USE_C99_PROTO -DPOLYBENCH_USE_RESTRICT -Ofast -ftree-vectorize -march=native -mtune=native -fvect-cost-model=unlimited -fsimd-cost-model=unlimited -mavx2 -ftree-vectorizer-verbose=7 --param min-vect-loop-bound=1"
          debug: False
      execution:
          th_pin: "OMP_NUM_THREADS=1 GOMP_CPU_AFFINITY=7"
          debug: False
