- kernel:
      name: "stream"
      path: "."
      description: "Setup for experiment autovectorization"
      debug:
          False
      preamble:
          command: "sudo cpupower frequency-set -u 3.7GHz  > /dev/null && sudo
                    cpupower frequency-set -d 3.7GHz > /dev/null"
      finalize:
          clean_tmp_files: False
          clean_asm_files: False
          clean_bin_files: False
          command: "echo 'done!'"
      compilation:
          debug: False
          enabled: True
          processes: 6
          language: "C"
          compiler_flags: { "gcc": [" -march=native -O3 -DTUNED -fno-inline -fopenmp"] }
          main_src: "stream.c"
          loop_type: C # if you choose "asm" loop type it may cause SIGSEV as it uses EDX register
          kernel_inlined: True
          asm_analysis:
              syntax: "intel"
              count_ins: False
              static_analysis: ""
      configuration:
          d_features:
              MARTA_NUM_THREADS:
                  evaluate: True
                  type: "static"
                  val_type: "numeric"
                  value: "[1,2,4,8]"
              OFFSET:
                  evaluate: True
                  type: "static"
                  val_type: "numeric"
                  value: "[8]"
              STREAM_ARRAY_SIZE:
                  evaluate: True
                  type: "static"
                  val_type: "numeric"
                    #value: "[33554432]"
                  value: "[8388608]"
              ADD_VERSION:
                  evaluate: True
                  type: "static"
                  val_type: "numeric"
                  value: "[0,11,12,13,14,21,22,23,24,25,26]"
                    #value: "[4]"
                    #              ASSIGNMENT_VERSION:
                    #                  evaluate: True
                    #                  type: "static"
                    #                  val_type: "numeric"
                    #                    #value: "list(range(2))"
                    #                  value: "[0]"
              STRIDE:
                  evaluate: True
                  type: "static"
                  val_type: "numeric"
                  value: "2**np.arange(21)"
              SW_PREFETCH:
                  evaluate: True
                  type: "static"
                  val_type: "numeric"
                    #value: "[0,1,2,4,8,16,32,64,128,256,512]"
                  value: "[0]"
          derived:
              BANDWIDTH:
                  type: single
                  variables: ["tsc", "STREAM_ARRAY_SIZE"]
                  expression: (3 * VAR_1 * 8) / (VAR_0/3.4) #3.4GHz is the base freq of Ryzen 5950X
      execution:
          stdout_redirect: "/tmp/TESTING_OUTPUT_MKS"
          enabled: True
          time: False
          papi_counters:  [ "MEM_LOAD_UOPS_RETIRED:L1_HIT", "MEM_LOAD_UOPS_RETIRED:L1_MISS", "L2_RQSTS:DEMAND_DATA_RD_HIT", "L2_RQSTS:DEMAND_DATA_RD_MISS", "LONGEST_LAT_CACHE:MISS", "MEM_LOAD_L3_MISS_RETIRED:LOCAL_DRAM", "MEM_INST_RETIRED:ALL_LOADS", "MEM_INST_RETIRED:ALL_STORES" ]
          tsc: True
          threshold_outliers: 3
          discard_outliers: True
          compute_avg: True
          nexec: 10
          nsteps: 1
          cpu_affinity: 11
          prefix: "taskset -c 11"
      output:
          name: "default"
          columns: "all"
          report: True
          verbose: True
