- kernel:
      name: "packing"
      path: "examples/packing/src/"
      description: "Setup for experiment gather"
      debug: False
      preamble:
          command: "sudo cpupower frequency-set -u 2.1GHz  > /dev/null && sudo
          cpupower frequency-set -d 2.1GHz > /dev/null"
      finalize:
          clean_tmp_files: False
          clean_asm_files: False
          clean_bin_files: False
          command: "echo 'done!'"
      compilation:
          enabled: True
          processes: 32
          language: "C"
          compiler_flags: 
            { 
                "gcc-11": [" -march=native -mtune=native -Ofast "],
                "icc": [" -march=native -mtune=native -Ofast "],
            }
          common_flags: " -D__INTEL_COMPILER_USE_INTRINSIC_PROTOTYPES "
          main_src: "main.c"
          kernel_inlined: True
          asm_analysis:
                syntax: "intel"
                count_ins: True
                static_analysis: ""
          debug: False
      configuration:
          kernel_cfg: [
          "-DNO_SIMD",
          "-DINSERTS",
          "-DINSERTS2",
          "-DBLENDS",
          ]
          d_features:
                N:
                    evaluate: True
                    type: "static"
                    val_type: "numeric"
                    value: "[1024]"
          flops: "8"
      execution:
          enabled: True
          papi_counters: ["INSTRUCTIONS_RETIRED"]
          time: True
          tsc: True
          threshold_outliers: 3
          mean_and_discard_outliers: True
          nexec: 7
          nsteps: 1
          cpu_affinity: 11
          prefix: ""
      output:
          name: "intel_xeon_silver"
          columns: "all"
          report: True
          verbose: True
