- kernel:
      input: examples/autovectorization/data/intel_xeon_silver_4216.csv
      output_path: examples/autovectorization/data/
      prepare_data:
          cols: N LOOP_BOUND_PARAMETRIC CFG compiler
          target: loops_vectorized
      plot:
          type: relplot
          format: png
          data: raw
          x_axis: index
          y_axis: loops_vectorized
          hue: N
          col: CFG
      classification:
          type: decision_tree
          config:
              max_depth: 3
              max_leaves: 10
              criterion: "gini"
              min_score: 0.8
              precision: 1
              pruning_mccp_alpha: 0.0
              text_tree: True
              graph_tree: True
              orientation: "vertical"
              labels: ["No vect.", "Vect."]
      feature_importance:
          type: random_forest
          config:
              n_estimators: 10
              criterion: "gini"
              max_depth: 10
              min_samples_split: 2
              min_samples_leaf: 1
              n_jobs: 1
              random_state: 0
