- kernel:
      name: "autovectorization"
      path: "examples/autovectorization/src/"
      description: "Setup for experiment autovectorization"
      debug: False
      preamble:
          command: "sudo cpupower frequency-set -u 2.1GHz  > /dev/null && sudo
          cpupower frequency-set -d 2.1GHz > /dev/null"
      finalize:
          clean_tmp_files: False
          clean_asm_files: False
          clean_bin_files: False
          command: "echo 'done!'"
      compilation:
          debug: False
          enabled: True
          processes: 32
          language: "C"
          compiler_flags: 
            { 
                "gcc-11": [" -march=native -mtune=native -Ofast "],
                "gcc": [" -march=native -mtune=native -Ofast "],
                "icc": [" -march=native -mtune=native -Ofast "],
            }
          main_src: "main.c"
          kernel_inlined: True
          asm_analysis:
                syntax: "intel"
                count_ins: False
                static_analysis: ""
      configuration:
          kernel_cfg: [
          "-DLOOP",
          "-DLOOP_PARTIAL_SLP",
          "-DLOOP_SLP",
        # "-DLOOP_NESTED",
        #   "-DLOOP_NESTED_DOUBLE"
          ]
          d_features:
                N:
                    evaluate: True
                    type: "static"
                    val_type: "numeric"
                    value: "[2,3,4,5,8,16,25,32,48,70,128,200,256,512]"
                LOOP_BOUND_PARAMETRIC:
                    evaluate: True
                    type: "static"
                    val_type: "numeric"
                    value: "[0,1]"
          flops: "1*N"
      execution:
          enabled: True
          papi_counters: ["INSTRUCTIONS_RETIRED"]
          time: True
          tsc: True
          threshold_outliers: 3
          mean_and_discard_outliers: True
          nexec: 5
          nsteps: 100
          cpu_affinity: 11
          prefix: ""
      output:
          name: "default"
          columns: "all"
          report: True
          verbose: True
