- kernel:
      input: examples/autovectorization/data/intel_xeon_silver_4216_fulldata.csv
      output_path: examples/autovectorization/data/
      prepare_data:
          cols: compiler N_ITER INIT_VAL ACC_STRIDE LOOP_STEP LOOP_BOUND_PARAMETRIC INDEX_FACTOR_PARAMETRIC LS_PARAM INIT_VAL_PARAMETRIC
          target: loops_vectorized
      plot:
          type: kdeplot
          format: pdf
          data: raw
          x_axis: N_ITER
          hue: loops_vectorized
          hatches: True
      classification:
          type: decision_tree
          config:
              style: "scikit"
              max_depth: 4
              max_leaves: 100
              criterion: "gini"
              min_score: 0.8
              precision: 3
              pruning_mccp_alpha: 0.0
              text_tree: True
              graph_tree: True
              proportion: True
              orientation: "horizontal"
              labels: ["No vect.", "Vect."]
      feature_importance:
          type: random_forest
          config:
              n_estimators: 10
              criterion: "gini"
              max_depth: 10
              min_samples_split: 2
              min_samples_leaf: 1
              n_jobs: 1
              random_state: 0
