# example file, this file should be used for executing with ubench.py
# POSSIBLE VALUES

- compilation:
    compiler: ["gcc"]
    kernel: ["kernel.c"]
    #init_val: [0, 1, 3, 7, 15, 16]
    init_val: [0]
    #tile_size: [1, 3, 4, 8, 12, 16]
    tile_size: [1]
    step_size: [1, 2 ]
    nexec: 7
    nruns: 1000000
    flops: 2
    custom_flags: ""
    debug: False
- execution:
    th_pin: ""
    debug: False
