- kernel:
      input: examples/loop_interchange/data/intel_xeon_silver_4216.csv
      output_path: examples/loop_interchange/data/
      prepare_data:
          cols: CFG LOOP_BOUND_PARAMETRIC ARRAY_DIM compiler
          target: loop_interchange
          norm: None
          categories:
              enabled: False
      plot:
          type: relplot
          format: pdf
          data: raw
          x_axis: CFG
          y_axis: loop_interchange
          hue: compiler_flags
          col: compiler
      classification:
          type: decision_tree
          config:
              max_depth: 3
              max_leaves: 10
              criterion: "gini"
              min_score: 0.8
              pruning_mccp_alpha: 0.0
              text_tree: True
              graph_tree: True
              orientation: "vertical"
              labels: ["No inter.", "Inter."]
              style: scikit
      feature_importance:
          type: random_forest
          config:
              n_estimators: 10
              criterion: "gini"
              max_depth: 10
              min_samples_split: 2
              min_samples_leaf: 1
              n_jobs: 1
              random_state: 0
