- kernel:
      name: "gather_scatter"
      path: "examples/gather_scatter/src/"
      description: "Setup for experiment gather"
      debug: False
      preamble:
          command: "sudo cpupower frequency-set -u 2.1GHz  > /dev/null && sudo
          cpupower frequency-set -d 2.1GHz > /dev/null"
      finalize:
          clean_tmp_files: False
          clean_asm_files: False
          clean_bin_files: False
          command: "echo 'done!'"
      compilation:
          enabled: True
          processes: 32
          language: "C"
          compiler_flags: 
            { 
                "gcc-11": [" -march=native -mtune=native -O3 "],
            }
          main_src: "main.c"
          kernel_inlined: True
          asm_analysis:
                syntax: "intel"
                count_ins: True
                static_analysis: ""
          debug: False
      configuration:
          kernel_cfg: [
          "-DGATHER",
          "-DSCATTER",
          ]
          d_features:
                IDX0:
                    evaluate: True
                    type: "static"
                    val_type: "numeric"
                    value: "[0,1,554]"
                IDX1:
                    evaluate: True
                    type: "static"
                    val_type: "numeric"
                    value: "[1,18,234]"
                IDX2:
                    evaluate: True
                    type: "static"
                    val_type: "numeric"
                    value: "[2,32,5]"
                IDX3:
                    evaluate: True
                    type: "static"
                    val_type: "numeric"
                    value: "[3,48,19]"
                IDX4:
                    evaluate: True
                    type: "static"
                    val_type: "numeric"
                    value: "[4,64,15]"
                IDX5:
                    evaluate: True
                    type: "static"
                    val_type: "numeric"
                    value: "[5,80,19]"
                IDX6:
                    evaluate: True
                    type: "static"
                    val_type: "numeric"
                    value: "[6,96,109]"
                IDX7:
                    evaluate: True
                    type: "static"
                    val_type: "numeric"
                    value: "[7,112,234]"
          derived:
            SET_:
                variables: ["IDX0", "IDX1", "IDX2", "IDX3", "IDX4", "IDX5", "IDX6", "IDX7"]
                expression: int(VAR/16) % 16
            CL_:
                variables: ["IDX0", "IDX1", "IDX2", "IDX3", "IDX4", "IDX5", "IDX6", "IDX7"]
                expression: int(VAR / 16)
            N_CL:
                type: all
                variables: ["CL_IDX0", "CL_IDX1", "CL_IDX2", "CL_IDX3",
                "CL_IDX4", "CL_IDX5", "CL_IDX6", "CL_IDX7"]
                expression: SIZE(UNIQUE(ALL_VAR))
          flops: "1"
      execution:
          enabled: True
          papi_counters: ["INSTRUCTIONS_RETIRED"]
          time: True
          tsc: True
          threshold_outliers: 3
          mean_and_discard_outliers: True
          nexec: 7
          nsteps: 10000
          cpu_affinity: 11
          prefix: ""
      output:
          name: "default"
          columns: "all"
          report: True
          verbose: True
