- kernel:
      input: examples/gather_scatter/data/intel_xeon_silver_4216.csv
      output_path: examples/gather_scatter/data/
      prepare_data:
          cols: N_SET N_CL
          rows: { "CFG": "-DSCATTER" }
          target: tsc
          norm: None
          categories:
              enabled: False
              scaling_factor: "1"
              mode: multimodal
      plot:
          type: kdeplot
          format: pdf
          data: raw
          x_axis: tsc
          log_scale: False
          hue: CFG
      classification:
          type: decision_tree
          enabled: True
          config:
              max_depth: 3
              random_state: 1
              criterion: "gini"
              splitter: "best"
              proportion: True
              max_leaves: 100
              text_tree: True
              graph_tree: True
              orientation: "horizontal"
      feature_importance:
          type: random_forest
          enabled: True
          config:
              n_estimators: 50
              criterion: "gini"
              max_depth: 50
              n_jobs: -1
              random_state: 0
