- kernel:
      input: examples/gather_scatter/data/intel_xeon_silver_4216.csv
      output_path: examples/gather_scatter/data/
      prepare_data:
          cols: N_CL N_SETS
          rows: { "CFG": "-DSCATTER" }
          target: FLOPSs
          norm: None
          categories:
              num: 2
              scaling_factor: 1e9
      plot:
          sort: FLOPSs
          type: relplot
          format: png
          data: raw
          x_axis: index
          y_axis: FLOPSs
          # hue: N_CL
          col: CFG
      classification:
          type: decision_tree
          config:
              max_depth: 3
              max_leaves: 10
              criterion: "gini"
              min_score: 0.8
              pruning_mccp_alpha: 0.0
              text_tree: True
              graph_tree: True
              orientation: "vertical"
      feature_importance:
          type: random_forest
          config:
              n_estimators: 10
              criterion: "gini"
              max_depth: 10
              min_samples_split: 2
              min_samples_leaf: 1
              n_jobs: 1
              random_state: 0
