- kernel:
      input: src/marta/analyzer/tmp/test.csv
      output_path: src/marta/analyzer/tmp/
      prepare_data:
          cols: I0 STEP_I J0 STEP_J N M INSTRUCTIONS_RETIRED
          target: FLOPSs
          norm: None
          categories:
              num: 3
      classification:
          type: decision_tree
          config:
              max_depth: 10
              max_leaves: 10
              criterion: "gini"
              min_score: 0.8
              pruning_mccp_alpha: 0.0
              text_tree: True
              graph_tree: True
              orientation: "horizontal"
      feature_importance:
          type: random_forest
          config:
              n_estimators: 10
              criterion: "gini"
              max_depth: 10
              min_samples_split: 2
              min_samples_leaf: 1
              n_jobs: 1
              random_state: 0
